### ISSUE TITLE
Error flow.start is not a function (with the example)

### ISSUE THREAD

**Issue by linuxonrails** [conceptualitis/easy-flow#1]
```javascript
var flow = require('easy-flow');

gulp.task('debug:watch', function () {
  flow.start();
  gulp.watch('./src/file.js', ['flow']);
});
```
I got:

```
[11:00:06] TypeError: flow.start is not a function
    at Gulp.<anonymous> (/home/davidm/src/todocoleccion/assets/javascripts/gulp_tasks/flow.js:13:8)
    at module.exports (/home/davidm/src/todocoleccion/assets/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/davidm/src/todocoleccion/assets/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/davidm/src/todocoleccion/assets/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/davidm/src/todocoleccion/assets/node_modules/orchestrator/index.js:134:8)
    at /home/davidm/src/todocoleccion/assets/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
```

**Comment by conceptualitis** [comment]
This was my bad, the command is `flow.watch();`.

I've updated the `README` and also bumped the version of `flow-bin` so that the binaries that need to be downloaded aren't as weird. Did that in aa58168183c575bd988355bffb21ebc9e9390153

Install version `0.0.2` and you should be good.
